import billingStandardPreviewUrl from "../assets/onboarding-billing-standard.png";
import developerPreviewUrl from "../assets/onboarding-developer.png";
import revenueStandardPreviewUrl from "../assets/onboarding-revenue-standard.png";
import { TEMPLATE_PREVIEW_TOP_ACCOUNTS_REF } from "./teamTemplate";
import type { HomepageTemplate } from "./teamTemplate";

const SEED_TIMESTAMP = "2026-01-15T12:00:00.000Z";

export const SEED_HOMEPAGE_TEMPLATES: HomepageTemplate[] = [
  {
    id: "billing-standard",
    name: "Billing Standard",
    description:
      "Get started fast with an out-of-the-box homepage that puts your most essential Zuora actions at your fingertips.",
    audience: "Billing Operations",
    dashboardWidgetIds: ["revenue-tasks", "file-upload", "run-report"],
    customWidgetRefs: [],
    status: "published",
    previewImageUrl: billingStandardPreviewUrl,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "revenue-standard",
    name: "Revenue Standard",
    description: "Get started quickly with essential revenue actions and helpful resources.",
    audience: "Revenue Operations",
    dashboardWidgetIds: ["revenue-overview", "revenue-tasks", "run-program", "file-upload"],
    customWidgetRefs: [],
    status: "published",
    previewImageUrl: revenueStandardPreviewUrl,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "developer",
    name: "Developer",
    description:
      "Power your integrations with real-time API visibility, performance insights, and error tracking.",
    audience: "Developers",
    dashboardWidgetIds: ["rc-search", "run-program", "file-upload"],
    customWidgetRefs: [],
    status: "published",
    previewImageUrl: developerPreviewUrl,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "billing-ops",
    name: "Billing Ops",
    description:
      "A shared homepage starter for billing operations teams with task tracking, file upload access, and an open-balance leaderboard.",
    audience: "Billing Operations",
    dashboardWidgetIds: ["revenue-tasks", "file-upload"],
    customWidgetRefs: [TEMPLATE_PREVIEW_TOP_ACCOUNTS_REF],
    status: "published",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "revenue-close",
    name: "Revenue Close",
    description: "Monitor close milestones, pending tasks, and reporting in one workspace.",
    audience: "Revenue Accounting",
    dashboardWidgetIds: ["revenue-progress", "revenue-tasks", "run-report"],
    customWidgetRefs: [],
    status: "published",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "finance-leadership",
    name: "Finance Leadership",
    description: "Executive overview of revenue performance, close status, and reporting.",
    audience: "Finance Leadership",
    dashboardWidgetIds: ["revenue-overview", "revenue-progress", "run-report"],
    customWidgetRefs: [],
    status: "published",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "collections-team",
    name: "Collections Team",
    description: "Prioritize collections work with tasks, uploads, and account visibility.",
    audience: "Collections",
    dashboardWidgetIds: ["revenue-tasks", "file-upload"],
    customWidgetRefs: [TEMPLATE_PREVIEW_TOP_ACCOUNTS_REF],
    status: "published",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "contract-admin",
    name: "Contract Administration",
    description: "Search contracts and run revenue programs from a focused homepage.",
    audience: "Contract Administration",
    dashboardWidgetIds: ["rc-search", "run-program", "revenue-tasks"],
    customWidgetRefs: [],
    status: "published",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "batch-operations",
    name: "Batch Operations",
    description: "Track active batches, uploads, and operational tasks together.",
    audience: "Batch Operations",
    dashboardWidgetIds: ["active-batches", "file-upload", "revenue-tasks"],
    customWidgetRefs: [],
    status: "published",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "executive-summary",
    name: "Executive Summary",
    description: "High-level revenue overview and close process status for leadership reviews.",
    audience: "Executives",
    dashboardWidgetIds: ["revenue-overview", "revenue-progress"],
    customWidgetRefs: [],
    status: "published",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "reporting-hub",
    name: "Reporting Hub",
    description: "Quick access to revenue reports and overview metrics.",
    audience: "Reporting Analysts",
    dashboardWidgetIds: ["run-report", "revenue-overview"],
    customWidgetRefs: [],
    status: "published",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "integration-monitor",
    name: "Integration Monitor",
    description: "Watch integrations, uploads, and contract search from one dashboard.",
    audience: "Integration Engineers",
    dashboardWidgetIds: ["rc-search", "file-upload", "run-program"],
    customWidgetRefs: [],
    status: "published",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "draft-billing-ops-v2",
    name: "Billing Ops v2",
    description: "Updated billing operations layout with expanded task coverage.",
    audience: "Billing Operations",
    dashboardWidgetIds: ["revenue-tasks", "file-upload", "run-report"],
    customWidgetRefs: [TEMPLATE_PREVIEW_TOP_ACCOUNTS_REF],
    status: "draft",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "draft-q2-close",
    name: "Q2 Close Readiness",
    description: "Draft homepage for quarterly close preparation and milestone tracking.",
    audience: "Revenue Accounting",
    dashboardWidgetIds: ["revenue-progress", "revenue-tasks"],
    customWidgetRefs: [],
    status: "draft",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "draft-partner-portal",
    name: "Partner Portal",
    description: "Prototype layout for partner-facing revenue visibility.",
    audience: "Partner Operations",
    dashboardWidgetIds: ["revenue-overview", "rc-search"],
    customWidgetRefs: [],
    status: "draft",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "draft-support-ops",
    name: "Support Operations",
    description: "Draft template for support teams monitoring customer billing activity.",
    audience: "Customer Support",
    dashboardWidgetIds: ["revenue-tasks", "run-report"],
    customWidgetRefs: [],
    status: "draft",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "draft-regional-emea",
    name: "Regional EMEA",
    description: "Regional homepage draft tailored for EMEA revenue teams.",
    audience: "EMEA Revenue",
    dashboardWidgetIds: ["revenue-overview", "revenue-progress", "file-upload"],
    customWidgetRefs: [],
    status: "draft",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
];
